I fixed the alignment bug
swapnilsparsh/30DaysOfJavaScript pull request #1025
Opened 2023-05-03 16:41 UTC by pabhi4881

fixed the alignment bug of link icon 

issue no - #1024

2023-05-04 13:27 UTC, swapnilsparsh requested changes
Why did you changed the spelling? It is wrong.

2023-05-04 19:05 UTC, pabhi4881 commented
Okay, will decreasing the margin between the link icon and text be okay?

2023-05-05 10:28 UTC, pabhi4881 commented
@swapnilsparsh I have reduced the padding between the link icon and text.

2023-05-05 12:05 UTC, swapnilsparsh requested changes

2023-05-05 12:05 UTC, swapnilsparsh commented on index.html
> -        <h4 style="font-size: 18px;">Word For Alphabet Speak Aloud</h4>
Again you are making changes with font-size. Dont change font size

2023-05-05 13:12 UTC, pabhi4881 commented
@swapnilsparsh fixed everything

2023-05-07 18:03 UTC, swapnilsparsh requested changes
It is not fixed yet. Just by adding padding 0px won't fix this.

2023-05-07 19:05 UTC, pabhi4881 commented
What else do I need to do, sir? I have set the padding to 0px, which has resulted in the default padding being set to 0 and the link icon being aligned properly. If there is anything else I need to do, please suggest it to me, sir.

2023-05-08 08:21 UTC, swapnilsparsh commented
@pabhi4881 "Movie TV Series Quote Generator" is not fixed yet.

2023-05-08 14:33 UTC, pabhi4881 commented
@swapnilsparsh fixed, Sir.

2023-05-09 13:22 UTC, merged