shell game added with updated readme
swapnilsparsh/30DaysOfJavaScript pull request #1446
Opened 2024-05-19 05:26 UTC by Tamilkumaran17

### 🛠️ Fixes Issue #1418

### 👨‍💻 Changes proposed and Brief Description

I have added the shell game and also updated the README content and also updated the index.html with my file link.

### ✅ Check List (Check all the applicable boxes) 

- [ ✅] My code doesn't break any part of the project
- [ ✅] This PR does not contain plagiarized content.
- [✅ ] My Addition/Changes works properly and matches the overall repo pattern.
- [✅ ] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/123346938/9d0c86e5-d794-4a34-9374-3afbf0cfee3e)

2024-05-19 05:43 UTC, Tamilkumaran17 commented
Can you please explain if any conflict may occurs, i will be very useful to me to resolve it!

2024-05-22 20:27 UTC, swapnilsparsh requested changes

2024-05-22 20:27 UTC, swapnilsparsh commented on index.html
Don't remove any project, just add your project.

2024-05-25 05:33 UTC, Tamilkumaran17 commented
i have resolved the changes. can you check if any conflicts occurs?

2024-05-25 18:28 UTC, swapnilsparsh requested changes
When someone fails to find the ball for the first time then game should end instead it does not end right not.

2024-05-26 02:36 UTC, Tamilkumaran17 commented
now the game conditions are changed according to your constrains. can you check for any conflicts?

2024-05-26 12:26 UTC, swapnilsparsh requested changes
1. You have just fixed the text and nothing else.
2. Everything is static no photos or anything else to make it look good
3. When game is over then user should not be able to choose other options and "play again" button should be there

2024-05-26 13:25 UTC, Tamilkumaran17 commented
here i have added the play again button as you mentioned with small animations.

2024-05-28 18:31 UTC, swapnilsparsh commented on 30DaysOfJavaScript/assets/116.png
Everything is working fine just update the screenshot

2024-05-29 03:32 UTC, Tamilkumaran17 commented on 30DaysOfJavaScript/assets/116.png
updated screenshot in assets file.

2024-05-29 17:12 UTC, swapnilsparsh requested changes

2024-05-29 17:12 UTC, swapnilsparsh commented on 30DaysOfJavaScript/assets/116.png
Image should not contain the browser and taskbar. Only project screenshot should be there.

2024-05-30 08:25 UTC, Tamilkumaran17 commented on 30DaysOfJavaScript/assets/116.png
updated!!

2024-06-01 20:05 UTC, swapnilsparsh approved these changes

2024-06-01 20:05 UTC, merged

2024-06-01 20:05 UTC, swapnilsparsh commented
@Tamilkumaran17 Thank you for contributing to this repo. Looking forward for more 🚀