Adding Guess the shape game
swapnilsparsh/30DaysOfJavaScript pull request #1592
Opened 2024-06-01 05:23 UTC by codewithganeshhh

### 🛠️ Fixes Issue #1426 

### 👨‍💻 Changes proposed and Brief Description:

- This project is built on a basic web tech stacks such as HTML, CSS and JavaScript.
- This is a single-player game.
- The player will tell the shape formed using dots.
- Options are given in the game.
- If player reaches to 10 points will win the game.
- If player looses all the 5 lives will lose the game.

### ✅ Check List (Check all the applicable boxes) 

- [✅] My code doesn't break any part of the project
- [✅] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅] The title of my pull request is a short description of the requested changes.

### 📷 Screenshots
![116](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/291eb451-468b-4a77-880a-40abfafc839d)

2024-06-01 05:24 UTC, codewithganeshhh commented
What is the reason Why Auto level fail ? @swapnilsparsh

2024-06-01 20:10 UTC, swapnilsparsh requested changes
Fix the conflicts

2024-06-02 06:31 UTC, codewithganeshhh commented
Hey Can you tell me what's the problem ? @swapnilsparsh

2024-06-03 20:52 UTC, swapnilsparsh approved these changes

2024-06-03 20:52 UTC, merged