Added Game CatchTheBall
swapnilsparsh/30DaysOfJavaScript pull request #1660
Opened 2024-06-04 08:41 UTC by shruti110503

Added the game successfully.

### 🛠️ Closes #1609  

### 👨‍💻 Changes proposed and Brief Description
I have added the game as proposed. It is made using html css and javascript. 

### ✅ Check List (Check all the applicable boxes) 

- [ ✓] My code doesn't break any part of the project
- [ ✓] This PR does not contain plagiarized content.
- [✓ ] My Addition/Changes works properly and matches the overall repo pattern.
- [ ✓] The title of my pull request is a short description of the requested changes.
![catch-the-ball](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/118251562/cc478743-e1e4-4180-a02f-c112f6303dfa)

### 📷 Screenshots

2024-06-06 20:20 UTC, swapnilsparsh requested changes
Add your project in index.html

2024-06-10 18:27 UTC, swapnilsparsh requested changes

2024-06-10 18:27 UTC, swapnilsparsh commented on index.html
> +      <a href="http://127.0.0.1:5500/117-CatchTheBall/index.html"><button class="button">Github</button></a>
This will not be you localhost url, update this.

2024-06-10 18:40 UTC, shruti110503 commented on index.html
> +      <a href="http://127.0.0.1:5500/117-CatchTheBall/index.html"><button class="button">Github</button></a>
@swapnilsparsh can you please help me as to how can i add my own localhost url

2024-06-10 18:55 UTC, swapnilsparsh commented on index.html
> +      <a href="http://127.0.0.1:5500/117-CatchTheBall/index.html"><button class="button">Github</button></a>
@shruti110503 Take reference from the other url which are there in the index.htm and make the required changes

2024-06-14 14:43 UTC, swapnilsparsh requested changes
Please resolve the conflict and still the URL is not right.

2024-06-17 18:20 UTC, swapnilsparsh requested changes
Please resolve the conflict and add your project in index.html also

2024-06-18 19:00 UTC, swapnilsparsh commented
@shruti110503 Not working on mobile

2024-06-21 14:17 UTC, swapnilsparsh commented
@shruti110503 Any updates ?

2024-06-21 18:14 UTC, shruti110503 commented
> @shruti110503 Any updates ?

please check now

2024-06-21 18:17 UTC, swapnilsparsh approved these changes

2024-06-21 18:17 UTC, merged

2024-06-21 18:18 UTC, swapnilsparsh commented
@shruti110503 Thank you for contributing to this repo. Looking forward for more 🚀